# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$DROPLET_SSH" > ../github_do.key
          sudo chmod 600 ../github_do.key
          ssh-keyscan -H ${{secrets.DROPLET_IP}} > ~/.ssh/known_hosts
        shell: bash
        env:
          DROPLET_SSH: ${{secrets.DROPLET_SSH}}
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install and Deploy 
        run: |
          ../deploy.sh ${{secrets.DROPLET_IP}}
        shell: bash
          
